#set text(size: 10pt, font: "New Computer Modern")
#set par(justify: true)
#set enum(numbering: n => [*(#n)*])
#let parts(body) = {set enum(numbering: n => strong(numbering("(a)",n))); body}
#let subparts(body) = {set enum(numbering: n => strong(numbering("(i)",n))); body}
#let solution(body) = block(
	stroke: 1pt + rgb(40, 40, 40, 200), radius: 1pt, width: 100%, inset: 1em, strong("Solution:") + v(0pt) + body
)
#let mb(body) = math.upright(math.bold(body))

#align(center, text(1.75em)[Rings and Modules -- Sheet 2\ Units, Irreducible elements])
#align(center, text(1.4em)[YOUR NAME HERE :)])
#align(center, text(1.2em)[Hilary Term 2025])

// version uploaded 2025-01-28




	
+ /* 1 */ Show that the ideal in $bb(Z)[x]$ generated by 2 and $x$ is not principal.
	
	
	
+ /* 2 */ Which ideals $I$ in $bb(Z)$ have the property that if $x^(n) in I$ for some $n$ then $x in I$?
	
	
	
+ /* 3 */ Describe the irreducible elements of the following rings
	#parts[
		+ /* 3a */ $bb(C)[x]$,
			
		+ /* 3b */ $bb(R)[x]$,
			
		+ /* 3c */ the ring $cal(O)$ of holomorphic functions on $bb(C)$.
	]
	
	
	
+ /* 4 */ Let $phi.alt: R -> S$ be a ring homomorphism.
	#parts[
		+ /* 4a */ Show that if $I$ is a prime ideal in $S$ then its preimage $phi.alt^(-1)(I)$ is prime in $R$.
			
		+ /* 4b */ Is the preimage of a maximal ideal maximal? Give a proof or counterexample.
	]
	
	
	
+ /* 5 */ Show that the ring $bb(Z)[i]$ of Gaussian integers is a Euclidean domain.
	
	
	
+ /* 6 */ Consider the ring $ 
		bb(Z)[sqrt(-5)]={a+b sqrt(-5): a, b in bb(Z)}.
	 $ We define the norm function $N: bb(Z)[sqrt(-5)] -> bb(Z)_(>= 0)$ by $ 
		N(a+b sqrt(-5))=a^(2)+5 b^(2) .
	 $
	#parts[
		+ /* 6a */ Using this function, find the units of the ring, and show that 2 is an irreducible element.
			
		+ /* 6b */ Find two inequivalent factorisations into irreducibles of 6, and deduce $bb(Z)[sqrt(-5)]$ is not a UFD.
	]
	
	
	
+ /* 7 */ Let $R$ be an integral domain containing a field $K$. Explain how $R$ may be viewed as a vector space over $K$. Show that if $R$ is finite-dimensional as a vector space over $K$, then $R$ is a field.
	
	
	
+ /* 8 */ Let $mb(k)$ be a field, and let $mb(k)[[x]]$ denote the ring of formal power series over $mb(k)$, that is power series $sum_(n=0)^(oo) a_(n) x^(n)$ where $a_(n) in mb(k)$, but where we do not require the radius of convergence to be positive. We multiply series in the usual way.
	#parts[
		+ /* 8a */ Find the units of $mb(k)[[x]]$.
			
		+ /* 8b */ Show there is a unique maximal ideal in $mb(k)[[x]]$.
			
		+ /* 8c */ Is $mb(k)[[x]]$ a Euclidean domain?
	]